# Preparation of custom RAG evaluation dataset

## Import LLM client

We use LLM hosted in Nebius AI-Studio:

In [9]:
import os
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

TEMPERATURE=0.1
TOP_P=0.95
MAX_TOKENS=2048

In [10]:
MODEL = "meta-llama/Meta-Llama-3.1-405B-Instruct"

llm_client = ChatOpenAI(
    base_url="https://api.studio.nebius.ai/v1/",
    api_key=os.environ.get("NB_AI_STUDIO_KEY"),
    model=MODEL,
    temperature=TEMPERATURE,
    top_p=TOP_P,
    max_tokens=MAX_TOKENS,
)

llm_client.invoke("What is the capital of France").content

'The capital of France is Paris.'

We will use an OSS LLM hosted on Nebius AI-Studio as a judge to power `mlflow.genai` metrics. For this we need to provide the local proxy server which handles the API calls to LLM. Run the following in your terminal:

```bash
poetry shell
export NB_AI_STUDIO_KEY=<your-ai-studio-key>
mlflow deployments start-server --config-path mlflow_config/model_config.yaml --port 5001
```

Import the 'deployement' to use as evaluator LLM and see if it works:

In [11]:
from mlflow.deployments import get_deploy_client

client = get_deploy_client("http://localhost:5001")

data = {
    "messages": [
        {
            "role": "user",
            "content": "What would happen if an asteroid the size of a basketball encountered the Earth traveling at 0.5c? Please provide your answer in .rst format for the purposes of documentation.",
        }
    ],
    "temperature": 0.5,
    "max_tokens": 100,
    "n": 1,
    "frequency_penalty": 0.2,
    "presence_penalty": 0.2,
}
print(client.predict(endpoint="ai-studio-chat", inputs=data)["choices"][0]["message"]["content"])

.. _asteroid-impact:

Asteroid Impact at 0.5c
=======================

Introduction
------------

This document explores the hypothetical scenario of an asteroid, approximately the size of a basketball (with a diameter of about 0.24 meters), encountering Earth while traveling at 0.5c (half the speed of light, or approximately 150,000,000 meters per second).

Impact Energy
-------------

The kinetic energy of an object

## Prepare evaluation dataset

### Generate QA pairs

In order to evaluate RAG ppeline, we need to have areference dataset which will include golden QA pairs together with reference context. 


To generate QA pairs we are going to use `jamescalam/ai-arxiv-chunked` which contains chunkd of NLP-related reseearch papers. We are not going to use the chunks themselves but only paper summaries which are provided together with chunks. 
There are over 400 unique summaries and we are going to sample 200 of them to use as source context for QA pairs generation

In [12]:
from datasets import load_dataset
import random

data = load_dataset("jamescalam/ai-arxiv-chunked", split="train")
summaries = list(set(data["summary"]))
sampled_summaries = random.sample(summaries, 200)

Let's make batches of 4 to accelerate the generation process

In [13]:
BATCH_SIZE = 4
batches = [sampled_summaries[i * BATCH_SIZE:(i+1) * BATCH_SIZE] for i in range(len(sampled_summaries)//BATCH_SIZE)]
len(batches)

50

We need to create some helper function which will process batches of summaries and generate QA pairs. It is usefull to wrap this function with `retry` in case we run into rate limit for example:

In [14]:
from langchain_core.prompts import ChatPromptTemplate
from tenacity import retry, wait_random_exponential, stop_after_attempt 

SYSTEM_PROMPT = """
Your task is to write a standalone factoid question and an answer given a context.
Your factoid question should be answerable with a specific, concise piece of factual information from the context.
Your factoid question should be formulated in the same style as questions users could ask in a search engine.
Your answer to the factoid question should be detailed and relying upon given context and be accessible for a wide variety of users.
This means that your standalone factoid question MUST NOT mention something like "according to the passage" or "context".

Provide your answer as follows:

Output:::
Factoid question: (your factoid question)
Answer: (your answer to the factoid question)"""

USER_PROMPT = """Now here is the context.

Context: {context}\n
Output:::"""

gen_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", SYSTEM_PROMPT),
        ("human", USER_PROMPT),
    ]
)

gen_prompt_template.batch(inputs=[{"context": "context"},{"context": "context"}])

@retry(wait=wait_random_exponential(multiplier=4, max=120), stop=stop_after_attempt(3))
def process_batch_messages(llm, batch):
    return llm.batch(gen_prompt_template.batch(inputs=[{"context": d} for d in batch]))

Some other helper functions which may be useful later:

In [15]:
import hashlib

def hash_string(input: str) -> str:
    h = hashlib.new('sha256')
    h.update(input.encode())
    
    return h.hexdigest()

from datetime import datetime

def get_timestamp() -> str:
    timestamp = datetime.now()
    return timestamp.strftime("%Y-%m-%d_%H-%M-%S")

Here's the code which processes the batches and parses the output into QA pairs:

In [16]:
import json
import mlflow
from tqdm import tqdm


formatted_timestamp = get_timestamp()
mlflow.set_experiment(f"Data generation for RAG eval {formatted_timestamp}")
mlflow.langchain.autolog()

file_path = f'syntetic_data/generated_items_{formatted_timestamp}.jsonl'

outputs = []
for batch in tqdm(batches[:]):
    responses = process_batch_messages(llm_client, batch)
    for response, doc in zip(responses, batch):
        output_QA_couple = response.content
        try:
            question = output_QA_couple.split("Factoid question: ")[-1].split("Answer: ")[0]
            answer = output_QA_couple.split("Answer: ")[-1]
            item =  {
                "document": {
                    "content": doc,
                    "collection_id": str(hash_string(doc)),
                },
                "question": question,
                "answer": answer,
            }
            outputs.append(item)
            json_line = json.dumps(item)
            with open(file_path, 'a') as file:
                file.write(json_line + '\n')
        except Exception as e:
            print(e.__str__())
            continue

2024/11/14 13:49:14 INFO mlflow.tracking.fluent: Experiment with name 'Data generation for RAG eval 2024-11-14_13-49-14' does not exist. Creating a new experiment.
2024/11/14 13:49:15 WARNING mlflow.utils.autologging_utils: You are using an unsupported version of langchain. If you encounter errors during autologging, try upgrading / downgrading langchain to a supported version, or try upgrading MLflow.
100%|██████████| 50/50 [06:45<00:00,  8.11s/it]

### (Optional) Evaluate generated eval dataset with `mlflow.genai` metrics

Let's use our `mlflow` deployement as LLM-as-a-judge to power evaluation metrics:

In [17]:
from mlflow.deployments import set_deployments_target

set_deployments_target("http://localhost:5001")

Let's use a built-in `mlflow` metric for relevance. We only need to provide the name of deployement specified in `model_config.yaml`

In [18]:
relevance_metric = mlflow.metrics.genai.relevance(
    model = "endpoints:/ai-studio-chat"
)

We will also need 2 additional metrics to evaluate for groundedness and autonomy. For this, we may use generic `genai` metric constructor `make_genai_metric()` provided by `mlflow`, which takes metric description and corresponding grading prompt:

In [19]:
groundedness_metric = mlflow.metrics.genai.make_genai_metric(
    name="groundedness",
    definition=(
        "Groundedness refers to how well the question is formulated to stay within the provided context, ensuring clarity "
        "and relevance to the task at hand. A grounded question should directly address the instruction, avoid ambiguity, "
        "and be clearly rooted in the context provided."
    ),
    grading_prompt=(
        "Groundedness: Evaluate if the question is formulated clearly, without ambiguity, and remains grounded in the provided Context. "
        "Below are the details for different scores: "
        "- Score 1: The question is vague or unclear and does not engage with the provided Context, making it impossible to discern "
        "how it relates to the question or instruction."
        "- Score 2: The question partially engages with the Context but includes significant ambiguities or unclear portions, often "
        "straying from the context or not fully addressing the question."
        "- Score 3: The question generally addresses the question using the provided Context but has occasional ambiguities or is "
        "unclear in certain aspects, making parts of the question less grounded."
        "- Score 4: The question is mostly clear and unambiguous, providing a grounded question based on the Context. However, there "
        "are minor instances where clarity could be improved or where the grounding in the context is weaker."
        "- Score 5: The question is entirely clear, unambiguous, and fully grounded in the provided Context. It aligns with context "
        "precisely with no unnecessary or unclear content."
    ),
    model="endpoints:/ai-studio-chat",
    parameters={"temperature": 0.0},
    aggregations=["mean", "variance"],
    greater_is_better=True,
)

standalone_metric = mlflow.metrics.genai.make_genai_metric(
    name="standalone",
    definition=(
        "Standalone refers to the degree to which the question can be understood and answered independently of any external "
        "context or information. A fully standalone question should be self-contained, meaning it does not rely on additional "
        "documents, previous interactions, or external scenarios to be complete or comprehensible."
    ),
    grading_prompt=(
        "Standalone: Evaluate if the question can be understood and answered without looking at the Context in the Instruction. "
        "Below are the details for different scores: "
        "- Score 1: The question heavily depends on external context or previous information to be understood. It refers to specific "
        "content (e.g., 'in the context' or 'in the document') and is incomplete on its own."
        "- Score 2: The question is mostly dependent on external information. While parts of the question may be clear, it still "
        "requires knowledge of additional context or documents to be fully understood."
        "- Score 3: The question is partially understandable on its own but still relies on some implicit context or background knowledge "
        "to be fully clear. It is incomplete without certain pieces of information."
        "- Score 4: The question is largely standalone and makes sense without needing much additional context. It may refer to specific "
        "technical details but can generally be understood independently."
        "- Score 5: The question is entirely self-contained and makes complete sense on its own. Even if technical terms or acronyms are used, "
        "a user with relevant expertise or access to documentation would understand it without needing additional context."
    ),
    model="endpoints:/ai-studio-chat",
    parameters={"temperature": 0.0},
    aggregations=["mean", "variance"],
    greater_is_better=True,
)

To evaluate generated QA dataset, we will use `mlflow.evaluate()` with a static dataset:

In [20]:
import pandas as pd

# simplify the QA generation instruction prompt for evaluation
instruction_prompt = """
Your task is to write a standalone factoid question and an answer given a context.
Your factoid question should be answerable with a specific, concise piece of factual information from the context.
Your factoid question should be formulated in the same style as questions users could ask in a search engine.

Context: {context}"""

eval_data = pd.DataFrame(
    {   
        "inputs": [instruction_prompt.format(context=' '.join(o["document"]["content"])) for o in outputs],
        "predictions": [f"""Question: {o["question"]}\n Answer: {o["answer"]}""" for o in outputs],
        "question": [o["question"] for o in outputs],
        "answer": [o["answer"] for o in outputs],
        "context": [o["document"]["content"] for o in outputs],
        "document": [o["document"] for o in outputs],
    }
)

with mlflow.start_run() as run:
    results = mlflow.evaluate(
        data=eval_data,
        predictions="predictions",
        extra_metrics=[
            groundedness_metric, 
            relevance_metric, 
            standalone_metric
        ],
    )
    
    print(f"Aggregated evaluation results: \n{results.metrics}")

Matplotlib is building the font cache; this may take a moment.
2024/11/14 13:56:39 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...
  0%|          | 0/1 [00:00<?, ?it/s]/Users/cyril-k/Library/Caches/pypoetry/virtualenvs/mlflow-llmops-z5YhI3Ul-py3.12/lib/python3.12/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
100%|██████████| 1/1 [00:01<00:00,  1.10s/it]
100%|██████████| 1/1 [00:00<00:00,  1.06it/s]
100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
100%|██████████| 200/200 [00:39<00:00,  5.07it/s]
100%|██████████| 200/200 [00:47<00:00,  4.20it/s]
100%|██████████| 200/200 [00:52<00:00,  3.80it/s]

Aggregated evaluation results:
{'groundedness/v1/mean': 5.0, 'groundedness/v1/variance': 0.0, 'relevance/v1/mean': 4.91, 'relevance/v1/variance': 0.08190000000000001, 'relevance/v1/p90': 5.0, 'standalone/v1/mean': 4.2, 'standalone/v1/variance': 0.15999999999999998}

2024/11/14 13:59:10 INFO mlflow.tracking._tracking_service.client: 🏃 View run rogue-rook-301 at: https://tracking.mlflow-e00rhqs1bwevnqy5wj.backbone-e00ffdgj3ybad7mxrx.msp.eu-north1.nebius.cloud/#/experiments/9/runs/77e4e2f2d9134863b0bcea487cbb6d3a.
2024/11/14 13:59:10 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: https://tracking.mlflow-e00rhqs1bwevnqy5wj.backbone-e00ffdgj3ybad7mxrx.msp.eu-north1.nebius.cloud/#/experiments/9.

Let's take a look at evaluation results table:

In [21]:
eval_results_table = results.tables["eval_results_table"]
eval_results_table

Downloading artifacts: 100%|██████████| 1/1 [00:01<00:00,  1.12s/it]
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00,  3.10it/s]

,inputs,question,answer,context,document,outputs,groundedness/v1/score,groundedness/v1/justification,relevance/v1/score,relevance/v1/justification,standalone/v1/score,standalone/v1/justification
0,\nYour task is to write a standalone factoid q...,What is the working principle of self-training...,The working principle of self-training algorit...,Semi-supervised algorithms aim to learn predic...,{'content': 'Semi-supervised algorithms aim to...,Question: What is the working principle of sel...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,4,The question is largely standalone and makes s...
1,\nYour task is to write a standalone factoid q...,What is the total number of questions in the A...,"The ARC dataset contains 7,787 questions, maki...","We present a new question set, text corpus, an...","{'content': 'We present a new question set, te...",Question: What is the total number of question...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,5,"The question ""What is the total number of ques..."
2,\nYour task is to write a standalone factoid q...,What is the average nDCG improvement of GPT-4 ...,GPT-4 outperforms the fully fine-tuned monoT5-...,Large Language Models (LLMs) have demonstrated...,{'content': 'Large Language Models (LLMs) have...,Question: What is the average nDCG improvement...,5,"The question is entirely clear, unambiguous, a...",5,The output answers the question comprehensivel...,4,The question is largely standalone and makes s...
3,\nYour task is to write a standalone factoid q...,What is GRUE in the context of natural languag...,"GRUE, or General Reinforced-language Understan...",We tackle the problem of aligning pre-trained ...,{'content': 'We tackle the problem of aligning...,Question: What is GRUE in the context of natur...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,4,The question is largely standalone and makes s...
4,\nYour task is to write a standalone factoid q...,What are the sources of the large-scale models...,The large-scale models were trained on two dif...,Advances in language modeling architectures an...,{'content': 'Advances in language modeling arc...,Question: What are the sources of the large-sc...,5,"The question is entirely clear, unambiguous, a...",4,The output directly answers the question by id...,4,The question is largely standalone and makes s...
...,...,...,...,...,...,...,...,...,...,...,...,...
195,\nYour task is to write a standalone factoid q...,What percentage of added toxicity is found acr...,Added toxicity across languages in machine tra...,Machine Translation systems can produce differ...,{'content': 'Machine Translation systems can p...,Question: What percentage of added toxicity is...,5,"The question is entirely clear, unambiguous, a...",4,The output answers the question and is consist...,4,The question is largely standalone and makes s...
196,\nYour task is to write a standalone factoid q...,What is the name of the dataset that significa...,The dataset is called MathQA. It is a large-sc...,We introduce a large-scale dataset of math wor...,{'content': 'We introduce a large-scale datase...,Question: What is the name of the dataset that...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,5,The question is entirely self-contained and ma...
197,\nYour task is to write a standalone factoid q...,How much of a dataset needs to be poisoned to ...,"Poisoning just 0.01% of a dataset (e.g., 300 i...",Multimodal contrastive learning methods like C...,{'content': 'Multimodal contrastive learning m...,Question: How much of a dataset needs to be po...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,4,The question is largely standalone and makes s...
198,\nYour task is to write a standalone factoid q...,"What percentage of test cases analogize ""Musli...","In 23% of test cases, ""Muslim"" is analogized t...",It has been observed that large-scale language...,{'content': 'It has been observed that large-s...,Question: What percentage of test cases analog...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,4,The question is largely standalone and makes s...
199,\nYour task is to write a standalone factoid q...,Where can the pretrained versions of the CTRL ...,The pretrained versions of the CTRL language m...,Large-scale language models show promising tex...,{'content': 'Large-scale language models show ...,Question: Where can the pretrained versions of...,5,"The question is entirely clear, unambiguous, a...",5,The output comprehensively answers the questio...,5,"The question ""Where can the pretrained version..."

The code which evaluates QA pairs updates the original items with evaluation scores and corresponding justification:

Let's take a look at the evaluation results:

In [22]:
import pandas as pd
import datasets

pd.set_option("display.max_colwidth", None)

print("Evaluation dataset before filtering:")
display(
    eval_results_table[
        [
            "question",
            "answer",
            "groundedness/v1/score",
            "relevance/v1/score",
            "standalone/v1/score",
        ]
    ]
)
generated_questions = eval_results_table.loc[
    (eval_results_table["groundedness/v1/score"] >= 4)
    & (eval_results_table["relevance/v1/score"] >= 4)
    & (eval_results_table["standalone/v1/score"] >= 5)
]
print("============================================")
print("Final evaluation dataset:")
display(
    generated_questions[
        [
            "question",
            "answer",
            "groundedness/v1/score",
            "relevance/v1/score",
            "standalone/v1/score",
        ]
    ]
)

eval_dataset = datasets.Dataset.from_pandas(generated_questions, split="train", preserve_index=False)

Evaluation dataset before filtering:

,question,answer,groundedness/v1/score,relevance/v1/score,standalone/v1/score
0,What is the working principle of self-training algorithms?\n,The working principle of self-training algorithms is to learn a classifier iteratively by assigning pseudo-labels to the set of unlabeled training samples with a margin greater than a certain threshold. These pseudo-labeled examples are then used to enrich the labeled training data and to train a new classifier in conjunction with the labeled training set.,5,5,4
1,What is the total number of questions in the ARC dataset?\n,"The ARC dataset contains 7,787 questions, making it the largest public-domain set of natural, grade-school science questions.",5,5,5
2,What is the average nDCG improvement of GPT-4 over the fully fine-tuned monoT5-3B on TREC datasets?\n,GPT-4 outperforms the fully fine-tuned monoT5-3B on TREC datasets by an average of 2.7 nDCG.,5,5,4
3,What is GRUE in the context of natural language processing?\n,"GRUE, or General Reinforced-language Understanding Evaluation, is a benchmark for evaluating reinforcement learning (RL) algorithms in natural language processing (NLP) tasks. It consists of 6 language generation tasks that are supervised by reward functions, which capture automated measures of human preference, rather than target strings. GRUE is the first leaderboard-style evaluation of RL algorithms for NLP tasks, aiming to assess the effectiveness of RL methods in aligning language models with human preferences.",5,5,4
4,What are the sources of the large-scale models' training corpora that exhibit considerable levels of bias?\n\n,"The large-scale models were trained on two different corpora: news articles and Wikipedia. These models exhibited considerable levels of bias, indicating that the training data has a significant impact on the sentiment of generated text.",5,4,4
...,...,...,...,...,...
195,What percentage of added toxicity is found across languages in machine translation systems?\n,"Added toxicity across languages in machine translation systems varies from 0% to 5%, with low-resource languages and certain demographic axes such as sexual orientation, gender and sex, and ability being more prone to added toxicity.",5,4,4
196,What is the name of the dataset that significantly enhances the AQuA dataset with fully-specified operational programs?\n\n,The dataset is called MathQA. It is a large-scale dataset of math word problems that uses a new representation language to model precise operation programs corresponding to each math problem. This dataset aims to improve both the performance and the interpretability of the learned models.,5,5,5
197,How much of a dataset needs to be poisoned to cause a model to misclassify test images by overlaying a small patch?\n,"Poisoning just 0.01% of a dataset (e.g., 300 images out of a 3 million-example dataset) can cause the model to misclassify test images by overlaying a small patch.",5,5,4
198,"What percentage of test cases analogize ""Muslim"" to ""terrorist"" in GPT-3's responses?\n\n","In 23% of test cases, ""Muslim"" is analogized to ""terrorist"" in GPT-3's responses, indicating a persistent Muslim-violence bias in the language model.",5,5,4
199,Where can the pretrained versions of the CTRL language model be accessed?\n,The pretrained versions of the CTRL language model can be accessed at https://github.com/salesforce/ctrl.,5,5,5

============================================
Final evaluation dataset:

,question,answer,groundedness/v1/score,relevance/v1/score,standalone/v1/score
1,What is the total number of questions in the ARC dataset?\n,"The ARC dataset contains 7,787 questions, making it the largest public-domain set of natural, grade-school science questions.",5,5,5
5,What is the performance gap between humans and machines on the NewsQA dataset?\n,"The performance gap between humans and machines on the NewsQA dataset is 0.198 in F1 score, indicating that there is still room for improvement through future research.",5,5,5
8,How many images are in the Fashion-MNIST training set?\n,"The Fashion-MNIST training set has 60,000 images.",5,5,5
9,What ROUGE-1 score did the neural network model with intra-attention achieve on the CNN/Daily Mail dataset?\n\n,"The neural network model with intra-attention achieved a 41.16 ROUGE-1 score on the CNN/Daily Mail dataset, surpassing the performance of previous state-of-the-art models.",5,5,5
19,What is the name of the open benchmark constructed for investigating the multi-step paradigm for program synthesis?\n\n,"The open benchmark constructed for investigating the multi-step paradigm for program synthesis is called the Multi-Turn Programming Benchmark (MTPB). It consists of 115 diverse problem sets that are factorized into multi-turn prompts, allowing researchers to test and evaluate the effectiveness of program synthesis models in a multi-step setting.",5,5,5
21,What is the state-of-the-art average accuracy achieved by Chinchilla on the MMLU benchmark?\n,"Chinchilla achieves a state-of-the-art average accuracy of 67.5% on the MMLU benchmark, which is a greater than 7% improvement over Gopher.",5,5,5
34,What is the name of the proposed automatic CoT prompting method?\n,"The proposed automatic CoT prompting method is called Auto-CoT, which samples questions with diversity and generates reasoning chains to construct demonstrations.",5,5,5
52,What are the tasks included in the Natural Language Decathlon (decaNLP) challenge?\n,"The Natural Language Decathlon (decaNLP) challenge spans ten tasks, which are: question answering, machine translation, summarization, natural language inference, sentiment analysis, semantic role labeling, zero-shot relation extraction, goal-oriented dialogue, semantic parsing, and commonsense pronoun resolution.",5,5,5
64,What is the term for the phenomenon where neural networks lose performance on previously learned tasks when new tasks are introduced sequentially?\n\n,"The phenomenon is called ""catastrophic forgetting."" It occurs when neural networks are trained on new tasks sequentially, causing them to lose performance on previously learned tasks. This is a significant challenge in developing neural networks that can learn continually from incoming data.",5,5,5
73,What is the top-1 accuracy achieved by EfficientNet-B7 on ImageNet?\n,EfficientNet-B7 achieves a state-of-the-art 84.3% top-1 accuracy on ImageNet.,5,5,5
77,What is the top-1 accuracy achieved by NASNet on the ImageNet dataset?\n,"NASNet achieves a state-of-the-art accuracy of 82.7% top-1 on the ImageNet dataset, which is 1.2% better than the best human-invented architectures.",5,5,5
79,What is the name of the new metric for measuring bias amplification introduced in the work?\n\n,"The new metric for measuring bias amplification is called Directional Bias Amplification, denoted as $\text{BiasAmp}_{\rightarrow}$. This metric aims to address the shortcomings of the previously introduced metric by decoupling different types of bias amplification and accounting for varying base rates of protected attributes.",5,5,5
91,What is the name of the proposed non-autoregressive decoder based on the discrete diffusion model for text-to-sound generation?\n\n,"The proposed non-autoregressive decoder based on the discrete diffusion model is named Diffsound. It predicts all mel-spectrogram tokens in one step and refines them in subsequent steps, aiming to produce the best results after several iterations.",5,5,5
95,What is the percentage improvement in BLEU achieved by the No Language Left Behind model compared to the previous state-of-the-art?\n\n,"The No Language Left Behind model achieves a 44% improvement in BLEU relative to the previous state-of-the-art. This improvement is a result of the development of a conditional compute model based on Sparsely Gated Mixture of Experts, as well as multiple architectural and training improvements to counteract overfitting. The model was evaluated using a human-translated benchmark, Flores-200, and combined human evaluation with a novel toxicity benchmark to assess translation safety. This significant improvement in BLEU score marks an important step towards realizing a universal translation system.",5,5,5
97,How many languages does the MLQA benchmark contain QA instances in?\n,"The MLQA benchmark contains QA instances in 7 languages, which are English, Arabic, German, Spanish, Hindi, Vietnamese, and Simplified Chinese.",5,5,5
101,When is the stock of high-quality language data predicted to be exhausted?\n,"The stock of high-quality language data is predicted to be exhausted soon, likely before 2026.",5,5,5
102,What is the Massive Text Embedding Benchmark (MTEB) and what does it cover?\n,"The Massive Text Embedding Benchmark (MTEB) is a comprehensive benchmark for text embeddings that spans 8 embedding tasks covering a total of 58 datasets and 112 languages. It aims to provide a more thorough evaluation of text embeddings across various tasks, enabling better tracking of progress in the field.",5,5,5
107,What are the three popular data types for studying attack and defense mechanisms in deep neural networks?\n,"The three popular data types for studying attack and defense mechanisms in deep neural networks are images, graphs, and text. These data types are commonly used in various machine learning tasks and are vulnerable to adversarial examples, which has led to increased interest in developing countermeasures to protect against such threats.",5,5,5
108,What are the two main sources of carbon emissions from computing systems?\n,"The two main sources of carbon emissions from computing systems are operational energy consumption, and hardware manufacturing and infrastructure.",5,5,5
113,What is a long-term goal of machine learning research?\n,"A long-term goal of machine learning research is to produce methods that are applicable to reasoning and natural language, particularly building an intelligent dialogue agent.",5,5,5
114,What is HANS in natural language inference systems?\n,"HANS stands for Heuristic Analysis for NLI Systems, a controlled evaluation set designed to determine whether statistical natural language inference models have adopted certain fallible syntactic heuristics. It contains many examples where these heuristics fail, allowing researchers to assess the performance of models in challenging cases.",5,5,5
121,What is the number of parameters in the Megatron-Turing NLG 530B language model?\n,"The Megatron-Turing NLG 530B (MT-NLG) language model has 530 billion parameters, making it the largest monolithic transformer-based language model.",5,5,5
130,What is the name of the dataset collected to study the characteristics of ChatGPT's responses compared to human experts?\n\n,"The dataset is called the Human ChatGPT Comparison Corpus (HC3), which consists of tens of thousands of comparison responses from both human experts and ChatGPT across various areas such as open-domain, financial, medical, legal, and psychological questions.",5,5,5
131,What is the name of the 540-billion parameter language model trained for few-shot learning tasks?\n\n,"The 540-billion parameter language model is called Pathways Language Model, abbreviated as PaLM. It is a densely activated, Transformer language model designed to further the understanding of the impact of scale on few-shot learning.",5,5,5
134,What ranking did AlphaCode achieve in simulated evaluations on recent programming competitions on the Codeforces platform?\n,"AlphaCode achieved an average ranking of top 54.3% in competitions with more than 5,000 participants on the Codeforces platform. This ranking showcases the system's ability to create novel solutions to complex programming problems that require deeper reasoning.",5,5,5
137,What is the purpose of the Holistic Evaluation of Language Models (HELM)?\n,"The purpose of the Holistic Evaluation of Language Models (HELM) is to improve the transparency of language models by providing a comprehensive evaluation framework that assesses their capabilities, limitations, and risks across a wide range of scenarios and metrics.",5,5,5
144,What does BERT stand for in the context of language representation models?\n,BERT stands for Bidirectional Encoder Representations from Transformers. It is a language representation model designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.,5,5,5
156,How many distinct task types are covered in the Super-NaturalInstructions benchmark?\n,"The Super-NaturalInstructions benchmark covers 76 distinct task types, including classification, extraction, infilling, sequence tagging, text rewriting, and text composition.",5,5,5
159,What is the performance of humans on the TriviaQA dataset compared to baseline algorithms?\n,"Humans achieve a performance of 80% on the TriviaQA dataset, significantly outperforming the two baseline algorithms presented, which achieve 23% and 40% performance, respectively. This suggests that the TriviaQA dataset is a challenging testbed for reading comprehension tasks.",5,5,5
161,How many tasks does the Beyond the Imitation Game benchmark (BIG-bench) currently consist of?\n\n,"The Beyond the Imitation Game benchmark (BIG-bench) currently consists of 204 tasks, which cover a diverse range of topics including linguistics, childhood development, math, common-sense reasoning, biology, physics, social bias, software development, and more. These tasks were contributed by 450 authors across 132 institutions and are designed to test the capabilities and limitations of language models.",5,5,5
164,How many papers from the ACL anthology were surveyed for research on race in NLP?\n,"79 papers from the ACL anthology were surveyed for research on race in NLP. These papers were analyzed to identify how NLP literature has considered race, revealing gaps in research and highlighting the need for proactive consideration of racial hierarchies in NLP model development.",5,5,5
169,What is the human performance accuracy in the CommonsenseQA dataset?\n,The human performance accuracy in the CommonsenseQA dataset is 89%.,5,5,5
172,What percentage of questions did the best language model answer truthfully in a benchmark test of truthfulness?\n\n,"The best language model was truthful on 58% of questions in a benchmark test of truthfulness, which is significantly lower than human performance at 94%. This suggests that even the best language models struggle to provide accurate and truthful answers, often generating false responses that mimic popular misconceptions.",5,5,5
178,How many loss measurements were taken during the course of training in the experimental data?\n\n,"The experimental data consists of a database of 71,638,836 loss measurements taken over the course of training for 168,160 individual models across 35 workloads.",5,5,5
179,What is the name of the new challenge dataset for commonsense inference that proves difficult for state-of-the-art models?\n\n,"The new challenge dataset is called HellaSwag. It was created using a data collection paradigm called Adversarial Filtering (AF), which involves a series of discriminators iteratively selecting an adversarial set of machine-generated wrong answers. This dataset is particularly challenging for state-of-the-art models, with an accuracy rate of less than 48%, despite being trivial for humans with an accuracy rate of over 95%.",5,5,5
185,What is the formula for the GELU activation function?\n,"The GELU activation function is defined as $x\Phi(x)$, where $\Phi(x)$ is the standard Gaussian cumulative distribution function. This formula represents the nonlinearity of the GELU, which weights inputs by their value rather than gating them by their sign.",5,5,5
191,What is the number of parameters in the GPT-3 model?\n,The GPT-3 model has 175 billion parameters.,5,4,5
192,What license is the new corpus of human post-edits of English to German NMT released under?\n\n,"The new corpus of human post-edits of English to German NMT is released under the CC BY-NC-SA 4.0 license. This license allows users to share and adapt the material, but they must give appropriate credit, provide a link to the license, and indicate if changes were made. Additionally, the license restricts commercial use of the material, and any adaptations or shares must be distributed under the same license.",5,5,5
196,What is the name of the dataset that significantly enhances the AQuA dataset with fully-specified operational programs?\n\n,The dataset is called MathQA. It is a large-scale dataset of math word problems that uses a new representation language to model precise operation programs corresponding to each math problem. This dataset aims to improve both the performance and the interpretability of the learned models.,5,5,5
199,Where can the pretrained versions of the CTRL language model be accessed?\n,The pretrained versions of the CTRL language model can be accessed at https://github.com/salesforce/ctrl.,5,5,5

In [23]:
len(eval_dataset)

40

It appears that we have only 1/4 of the generated QA pairs which scored 5/5 on every metric. Proceed to save the filtered dataset:

In [24]:
eval_dataset.save_to_disk("NLP_eval_dataset_demo")

Saving the dataset (1/1 shards): 100%|██████████| 40/40 [00:00<00:00, 9012.74 examples/s]